// ============================================
// STYLES - LIVE RESULTS SYSTEM
// ============================================

export const styles = {
  // ============================================
  // BASE LAYOUT
  // ============================================
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    backgroundImage: 'url(https://www.scoutsjuventamerchtem.be/assets/img/logo.png)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundAttachment: 'fixed',
    padding: '20px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  content: {
    maxWidth: '1400px',
    margin: '0 auto',
  },
  
  // ============================================
  // LANDING PAGE
  // ============================================
  landingContent: {
    maxWidth: '800px',
    margin: '0 auto',
    textAlign: 'center',
    paddingTop: '60px',
  },
  title: {
    fontSize: '48px',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: '10px',
  },
  subtitle: {
    fontSize: '18px',
    color: '#666',
    marginBottom: '50px',
  },
  buttonGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '20px',
    marginTop: '30px',
  },
  card: {
    backgroundColor: 'white',
    padding: '40px',
    borderRadius: '12px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  icon: {
    color: '#666',
    marginBottom: '15px',
  },
  cardTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: '10px',
  },
  cardText: {
    fontSize: '14px',
    color: '#666',
    marginBottom: '20px',
  },
  input: {
    width: '100%',
    padding: '16px',
    fontSize: '20px',
    textAlign: 'center',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    fontWeight: 'bold',
    letterSpacing: '4px',
    textTransform: 'uppercase',
  },
  primaryButton: {
    width: '100%',
    padding: '16px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '10px',
    transition: 'background-color 0.2s',
  },

  // ============================================
  // HOST DASHBOARD - LIVE RESULTS
  // ============================================
  hostHeader: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    marginBottom: '30px',
    border: '2px solid #e5e7eb',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  hostHeaderLeft: {
    flex: 1,
  },
  hostTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: '5px',
  },
  hostSubtitle: {
    fontSize: '16px',
    color: '#6b7280',
  },
  hostHeaderRight: {
    display: 'flex',
    gap: '20px',
    alignItems: 'center',
  },
  bulkActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  bulkActionButton: {
    padding: '10px 14px',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  bulkActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  bulkActionButton: {
    padding: '10px 14px',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  statsBox: {
    backgroundColor: '#f9fafb',
    padding: '15px 25px',
    borderRadius: '8px',
    border: '2px solid #e5e7eb',
    textAlign: 'center',
  },
  statsLabel: {
    display: 'block',
    fontSize: '12px',
    color: '#6b7280',
    marginBottom: '5px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  statsNumber: {
    display: 'block',
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#2563eb',
  },
  codeBox: {
    textAlign: 'right',
  },
  codeLabel: {
    display: 'block',
    fontSize: '12px',
    color: '#6b7280',
    marginBottom: '5px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  codeDisplay: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    backgroundColor: '#f9fafb',
    padding: '12px 15px',
    borderRadius: '8px',
    border: '2px solid #e5e7eb',
  },
  codeText: {
    fontSize: '24px',
    fontWeight: 'bold',
    letterSpacing: '3px',
    color: '#111827',
  },
  iconButton: {
    padding: '8px',
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#6b7280',
    borderRadius: '4px',
    transition: 'background-color 0.2s',
  },

  // ============================================
  // QUESTION CARDS
  // ============================================
  questionsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '25px',
  },
  newQuestionCard: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    border: '2px dashed #cbd5f5',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  summaryCard: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  summaryHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  summaryTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: '700',
    color: '#111827',
  },
  summaryToggle: {
    padding: '10px 14px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#2563eb',
    color: 'white',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  summaryContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  summaryQuestion: {
    padding: '16px',
    borderRadius: '10px',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
  },
  summaryQuestionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#111827',
    marginBottom: '12px',
  },
  summaryAnswers: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  summaryAnswerRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  summaryAnswerLabel: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
  },
  summaryAnswerNames: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  summaryEmpty: {
    fontSize: '12px',
    color: '#9ca3af',
  },
  summaryCard: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  summaryHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  summaryTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: '700',
    color: '#111827',
  },
  summaryToggle: {
    padding: '10px 14px',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#2563eb',
    color: 'white',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  summaryContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  summaryQuestion: {
    padding: '16px',
    borderRadius: '10px',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
  },
  summaryQuestionTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#111827',
    marginBottom: '12px',
  },
  summaryAnswers: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  summaryAnswerRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  summaryAnswerLabel: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
  },
  summaryAnswerNames: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  summaryEmpty: {
    fontSize: '12px',
    color: '#9ca3af',
  },
  newQuestionHeader: {
    marginBottom: '20px',
  },
  newQuestionTitle: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
    marginBottom: '6px',
  },
  newQuestionSubtitle: {
    fontSize: '14px',
    color: '#6b7280',
    margin: 0,
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '16px',
  },
  formLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  textInput: {
    padding: '14px 16px',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
    fontSize: '16px',
    outline: 'none',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '12px',
  },
  smallInput: {
    padding: '12px 14px',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
    fontSize: '14px',
    outline: 'none',
  },
  helperText: {
    fontSize: '13px',
    color: '#ef4444',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '14px',
    color: '#374151',
    marginBottom: '16px',
  },
  addButton: {
    padding: '12px 18px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  newQuestionCard: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    border: '2px dashed #cbd5f5',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  newQuestionHeader: {
    marginBottom: '20px',
  },
  newQuestionTitle: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
    marginBottom: '6px',
  },
  newQuestionSubtitle: {
    fontSize: '14px',
    color: '#6b7280',
    margin: 0,
  },
  formRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '16px',
  },
  formLabel: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  textInput: {
    padding: '14px 16px',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
    fontSize: '16px',
    outline: 'none',
  },
  optionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '12px',
  },
  smallInput: {
    padding: '12px 14px',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
    fontSize: '14px',
    outline: 'none',
  },
  helperText: {
    fontSize: '13px',
    color: '#ef4444',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '14px',
    color: '#374151',
    marginBottom: '16px',
  },
  addButton: {
    padding: '12px 18px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  questionCard: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
  },
  questionCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '25px',
    paddingBottom: '20px',
    borderBottom: '2px solid #f3f4f6',
  },
  questionCardTitleSection: {
    flex: 1,
  },
  questionCardNumber: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: '#2563eb',
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  questionCardTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
  },
  questionCardActions: {
    display: 'flex',
    gap: '10px',
  },
  showVotersButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 14px',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  showVotersButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '10px 14px',
    border: 'none',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  toggleQuestionButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '12px 20px',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  resetButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px',
    backgroundColor: '#f3f4f6',
    color: '#6b7280',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },

  // ============================================
  // RESULTS SECTION
  // ============================================
  resultsSection: {
    marginTop: '20px',
  },
  resultsSummary: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '20px',
    padding: '12px',
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
  },
  totalVotesText: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#374151',
  },
  resultsGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  resultItem: {
    padding: '15px',
    backgroundColor: '#f9fafb',
    borderRadius: '8px',
    border: '1px solid #e5e7eb',
  },
  resultItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  resultItemLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  colorDot: {
    width: '12px',
    height: '12px',
    borderRadius: '50%',
  },
  resultItemText: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#374151',
  },
  resultItemCount: {
    fontSize: '15px',
    fontWeight: 'bold',
    color: '#111827',
  },
  progressBar: {
    width: '100%',
    height: '8px',
    backgroundColor: '#e5e7eb',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    transition: 'width 0.3s ease',
    borderRadius: '4px',
  },
  resultVoters: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '10px',
  },
  voterTag: {
    fontSize: '12px',
    color: '#111827',
    backgroundColor: '#e5e7eb',
    padding: '4px 8px',
    borderRadius: '999px',
  },
  resultVoters: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '10px',
  },
  voterTag: {
    fontSize: '12px',
    color: '#111827',
    backgroundColor: '#e5e7eb',
    padding: '4px 8px',
    borderRadius: '999px',
  },
  activeBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginTop: '20px',
    padding: '12px',
    backgroundColor: '#ecfdf5',
    borderRadius: '8px',
    border: '1px solid #10b981',
    color: '#065f46',
    fontSize: '14px',
    fontWeight: '600',
  },
  pulseDot: {
    width: '10px',
    height: '10px',
    backgroundColor: '#10b981',
    borderRadius: '50%',
    animation: 'pulse 2s infinite',
  },

  // ============================================
  // PARTICIPANT VIEW
  // ============================================
  participantContainer: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '20px',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  participantContent: {
    maxWidth: '900px',
    margin: '0 auto',
  },
  participantHeaderSection: {
    textAlign: 'center',
    marginBottom: '40px',
  },
  sessionBadgeParticipant: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    backgroundColor: 'white',
    padding: '10px 20px',
    borderRadius: '20px',
    border: '2px solid #e5e7eb',
    fontSize: '14px',
    fontWeight: '600',
    marginBottom: '20px',
  },
  statusDotParticipant: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#10b981',
  },
  participantMainTitle: {
    fontSize: '36px',
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: '10px',
  },
  waitingText: {
    fontSize: '16px',
    color: '#6b7280',
  },
  participantQuestionCard: {
    backgroundColor: 'white',
    padding: '30px',
    borderRadius: '12px',
    marginBottom: '30px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  participantQuestionHeader: {
    marginBottom: '25px',
    paddingBottom: '20px',
    borderBottom: '2px solid #f3f4f6',
  },
  participantQuestionNumber: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: '#2563eb',
    marginBottom: '10px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  participantQuestionTitle: {
    fontSize: '28px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
  },
  participantButtonsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '15px',
  },
  participantButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '20px',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: '600',
    transition: 'transform 0.2s, box-shadow 0.2s',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  participantButtonContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '5px',
    flex: 1,
  },
  participantButtonNumber: {
    fontSize: '14px',
    opacity: 0.9,
    fontWeight: 'bold',
  },
  participantButtonLabel: {
    fontSize: '18px',
    fontWeight: 'bold',
  },
  closedQuestionsSection: {
    marginTop: '40px',
    padding: '20px',
    backgroundColor: 'white',
    borderRadius: '12px',
    border: '2px solid #e5e7eb',
  },
  closedQuestionsTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontSize: '16px',
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: '15px',
  },
  closedQuestionsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  closedQuestionItem: {
    padding: '12px',
    backgroundColor: '#f9fafb',
    borderRadius: '6px',
    display: 'flex',
    gap: '10px',
  },
  closedQuestionNumber: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#9ca3af',
  },
  closedQuestionText: {
    fontSize: '14px',
    color: '#6b7280',
  },

  // ============================================
  // MODAL (QR CODE)
  // ============================================
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '30px',
    maxWidth: '500px',
    width: '90%',
    maxHeight: '90vh',
    overflow: 'auto',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
  },
  closeButton: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '5px',
    color: '#6b7280',
  },
  qrContainer: {
    textAlign: 'center',
  },
  qrImage: {
    width: '300px',
    height: '300px',
    border: '2px solid #e5e7eb',
    borderRadius: '8px',
    padding: '10px',
    backgroundColor: 'white',
  },
  qrText: {
    fontSize: '16px',
    color: '#6b7280',
    marginTop: '15px',
    marginBottom: '10px',
  },
  qrSubText: {
    fontSize: '14px',
    color: '#9ca3af',
    marginTop: '10px',
  },
  qrCodeBox: {
    backgroundColor: '#f9fafb',
    padding: '15px',
    borderRadius: '8px',
    border: '2px solid #e5e7eb',
    marginTop: '10px',
  },
  qrCodeText: {
    fontSize: '32px',
    fontWeight: 'bold',
    letterSpacing: '5px',
    color: '#111827',
  },

  // OLD COMPATIBILITY
  label: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '5px',
  },
  code: {
    fontSize: '24px',
    fontWeight: 'bold',
    letterSpacing: '3px',
    color: '#333',
  },
  pageTitle: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: '5px',
  },
  pageSubtitle: {
    fontSize: '16px',
    color: '#666',
  },

  // ============================================
  // NAME INPUT FORM
  // ============================================
  nameFormContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
  },
  nameFormContent: {
    backgroundColor: 'white',
    padding: '50px',
    borderRadius: '16px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    maxWidth: '500px',
    width: '90%',
    textAlign: 'center',
  },
  nameFormTitle: {
    fontSize: '42px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
    marginBottom: '15px',
  },
  nameFormSubtitle: {
    fontSize: '16px',
    color: '#6b7280',
    margin: 0,
    marginBottom: '30px',
  },
  nameForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  nameFormLabel: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  nameFormInput: {
    padding: '16px',
    fontSize: '18px',
    border: '2px solid #e5e7eb',
    borderRadius: '10px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  nameFormButton: {
    padding: '16px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    marginTop: '10px',
  },

  // ============================================
  // NAME INPUT FORM
  // ============================================
  nameFormContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
  },
  nameFormContent: {
    backgroundColor: 'white',
    padding: '50px',
    borderRadius: '16px',
    border: '2px solid #e5e7eb',
    boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
    maxWidth: '500px',
    width: '90%',
    textAlign: 'center',
  },
  nameFormTitle: {
    fontSize: '42px',
    fontWeight: 'bold',
    color: '#111827',
    margin: 0,
    marginBottom: '15px',
  },
  nameFormSubtitle: {
    fontSize: '16px',
    color: '#6b7280',
    margin: 0,
    marginBottom: '30px',
  },
  nameForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  nameFormLabel: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#374151',
    textAlign: 'left',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  nameFormInput: {
    padding: '16px',
    fontSize: '18px',
    border: '2px solid #e5e7eb',
    borderRadius: '10px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  nameFormButton: {
    padding: '16px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    marginTop: '10px',
  },
};